version: '3.9'

services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/data.sql
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata: